# Included AFTER normal project creation. Reference sources stay in place.
if(NOT TRAINING_VARIANT STREQUAL "student")
  return()
endif()
set(LAB_DIR "${CMAKE_SOURCE_DIR}/exercises/${SELECTED_DIR}")
set(LAB_TARGET "project${TRAINING_PROJECT}")
# Only this target's main is replaced. The CAN peer remains a reference target.
get_target_property(LAB_SOURCES ${LAB_TARGET} SOURCES)
list(REMOVE_ITEM LAB_SOURCES "src/main.c")
list(APPEND LAB_SOURCES "${LAB_DIR}/src/main.c")
if(TRAINING_PROJECT STREQUAL "05")
  list(REMOVE_ITEM LAB_SOURCES "src/temperature_monitor.c")
  list(APPEND LAB_SOURCES "${LAB_DIR}/src/temperature_monitor.c")
endif()
set_property(TARGET ${LAB_TARGET} PROPERTY SOURCES "${LAB_SOURCES}")

# Platform replacements occur only in labs with no CAN peer.
foreach(MODULE board_io timebase console)
  if(EXISTS "${LAB_DIR}/src/${MODULE}.c")
    get_target_property(PLATFORM_SOURCES stm32f4_platform SOURCES)
    list(REMOVE_ITEM PLATFORM_SOURCES "src/${MODULE}.c")
    list(APPEND PLATFORM_SOURCES "${LAB_DIR}/src/${MODULE}.c")
    set_property(TARGET stm32f4_platform PROPERTY SOURCES "${PLATFORM_SOURCES}")
  endif()
endforeach()

# A separate library avoids accidentally giving the peer a student protocol.
if(TRAINING_PROJECT MATCHES "^(06|09|10)$")
  set(STUDENT_COMMON_SOURCES "")
  foreach(MODULE training_can_protocol training_fault_manager training_ecu)
    if(EXISTS "${LAB_DIR}/src/${MODULE}.c")
      list(APPEND STUDENT_COMMON_SOURCES "${LAB_DIR}/src/${MODULE}.c")
    else()
      list(APPEND STUDENT_COMMON_SOURCES "${CMAKE_SOURCE_DIR}/common/src/${MODULE}.c")
    endif()
  endforeach()
  add_library(training_student_common STATIC ${STUDENT_COMMON_SOURCES})
  target_include_directories(training_student_common PUBLIC "${CMAKE_SOURCE_DIR}/common/include")
  target_link_libraries(training_student_common PUBLIC stm32f4_platform)
  get_target_property(LAB_LIBS ${LAB_TARGET} LINK_LIBRARIES)
  list(REMOVE_ITEM LAB_LIBS training_common)
  list(APPEND LAB_LIBS training_student_common)
  set_property(TARGET ${LAB_TARGET} PROPERTY LINK_LIBRARIES "${LAB_LIBS}")
endif()
message(STATUS "Student exercise: ${LAB_DIR} (unfinished starters intentionally do not pass acceptance)")

